<a href="https://colab.research.google.com/github/Amitdutta121/Food-recommender-system-ML-/blob/master/competition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install xgboost
!pip install dask[delayed] dask-ml
!pip install scikit-mdr skrebate

In [0]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans

In [0]:
df = pd.read_csv('data.csv', delimiter=',')
df.head()

user_id       item_id  ...  restaurant_id  item_count
0 -6088859261566846925  601d4dc5-2ad  ...   706247b3-86e           1
1 -4662982070704311223  af48a23f-f80  ...   ea90883c-a2f           1
2 -4849981472186386714  bab8cfae-930  ...   d9ab8a13-380           1
3 -5400975689533971605  3ae9d553-282  ...   0b8d021a-c5c           1
4  4810905585891548302  3d673534-8f8  ...   5772716f-1f3           1

[5 rows x 8 columns]

In [0]:
df = df.dropna(axis = 0, how ='any') 
df_back = df
df = df[['dow','hod','category_id']]
df.head()

dow  hod   category_id
0    7    3  9c64431e-79f
1    7    2  a989cb37-db5
2    1    1  4f31b9ea-059
3    4    0  37d510f8-745
4    3    1  4264559d-470

In [0]:
df['category_id'] = df['category_id'].apply(str)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
labelencoder = LabelEncoder()
df.iloc[:,2] = labelencoder.fit_transform(df.iloc[:,2])

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [0]:
df['category_id'].max(axis=0)

15129

In [0]:
kmeans = KMeans(n_clusters=50,init='k-means++')
kmeans.fit(df)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=50, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [0]:
labels = kmeans.predict(df)
centroids = kmeans.cluster_centers_


In [0]:
df['clusters'] = labels

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
df_back.head()

user_id       item_id  ...  restaurant_id  item_count
0 -6088859261566846925  601d4dc5-2ad  ...   706247b3-86e           1
1 -4662982070704311223  af48a23f-f80  ...   ea90883c-a2f           1
2 -4849981472186386714  bab8cfae-930  ...   d9ab8a13-380           1
3 -5400975689533971605  3ae9d553-282  ...   0b8d021a-c5c           1
4  4810905585891548302  3d673534-8f8  ...   5772716f-1f3           1

[5 rows x 8 columns]

In [0]:
df_back['cusine_id'] = df_back['cusine_id'].apply(str)

In [0]:
labelencoder = LabelEncoder()
df_back.iloc[:,5] = labelencoder.fit_transform(df_back.iloc[:,5])

In [0]:
df.head()

dow  hod  category_id  clusters
0    7    3         9164         3
1    7    2        10000        15
2    1    1         4599         6
3    4    0         3259        44
4    3    1         3835        48

In [0]:
df_back = df_back.drop(['dow','hod','category_id'], axis=1)

In [0]:
df_back['dow'] = df['dow'].values
df_back['hod'] = df['hod'].values
df_back['category_id'] = df['category_id'].values
df_back['clusters'] = df['clusters'].values

In [0]:
df_back['cusine_id'].max(axis=0)

45

In [0]:
df_back.head()

user_id       item_id  cusine_id  ... hod  category_id  clusters
0 -6088859261566846925  601d4dc5-2ad         44  ...   3         9164         3
1 -4662982070704311223  af48a23f-f80         24  ...   2        10000        15
2 -4849981472186386714  bab8cfae-930         14  ...   1         4599         6
3 -5400975689533971605  3ae9d553-282         35  ...   0         3259        44
4  4810905585891548302  3d673534-8f8         14  ...   1         3835        48

[5 rows x 9 columns]

In [0]:
X = df_back.iloc[:,5:9].values
Y = df_back.iloc[:,2:3].values

In [0]:
from keras.utils import to_categorical

# Y = to_categorical(Y)

Using TensorFlow backend.


In [0]:
Y

array([[44],
       [24],
       [14],
       ...,
       [45],
       [45],
       [45]])

In [0]:
# from sklearn.preprocessing import StandardScaler

# sc = StandardScaler()
# X = sc.fit_transform(X)
# X

In [0]:
# X.shape

In [0]:
# sc1 = StandardScaler()
# Y = sc.fit_transform(Y)
# Y

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [0]:
X_train

array([[    5,    20,  5685,    28],
       [    5,     5,  7762,    26],
       [    6,    16, 14017,    27],
       ...,
       [    1,     1,  1459,    29],
       [    1,    22, 13063,    31],
       [    7,    19,  1323,    13]])

In [0]:
import numpy as np
import pandas as pd
from sklearn.cluster import FeatureAgglomeration
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from xgboost import XGBClassifier

In [0]:

tX = df_back.iloc[:,5:9].values
tY = df_back.iloc[:,2:3].values

training_features, testing_features, training_target, testing_target = \
            train_test_split(tX, tY.ravel(), random_state=42, test_size=0.2)

exported_pipeline = make_pipeline(
    RFE(estimator=ExtraTreesClassifier(criterion="gini", max_features=0.1, n_estimators=100), step=0.55),
    FeatureAgglomeration(affinity="l2", linkage="average"),
    XGBClassifier(learning_rate=0.5, max_depth=7, min_child_weight=1, n_estimators=100, nthread=1, subsample=0.55)
)


exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features) 

In [0]:
from sklearn.metrics import confusion_matrix

result = confusion_matrix(testing_target, results)
result[3]

array([  6,   0,   2, 100,   0,   1,   0,   0,   0,   0,   0,   0,  10,
         0,   1,   0,   0,   1,   0])

In [0]:
#compare output

for i in range(len(testing_target)):
	print("X=%s, predicted=%s" % (testing_target[i], results[i]))

X=0, predicted=0
X=0, predicted=0
X=13, predicted=13
X=0, predicted=0
X=7, predicted=7
X=0, predicted=0
X=0, predicted=0
X=3, predicted=3
X=0, predicted=0
X=0, predicted=0
X=19, predicted=19
X=9, predicted=9
X=18, predicted=18
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=5, predicted=1
X=0, predicted=0
X=3, predicted=3
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=2, predicted=2
X=0, predicted=0
X=14, predicted=13
X=0, predicted=0
X=3, predicted=3
X=13, predicted=13
X=10, predicted=10
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=13, predicted=13
X=0, predicted=0
X=7, predicted=7
X=10, predicted=10
X=2, predicted=2
X=3, predicted=3
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=0, predicted=0
X=11, predicted=11
X=0, predicted=0
X=0, predicted=0
X=15, predicted=15
X=2, predicted=2
X=1, predicted=1
X=0, predicted=0
X=0, predicted=0
X=14, predi

In [0]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, results)

In [0]:
# for i in range(len(X_test)):
# 	print("X=%s, Predicted=%s" % (X_test[i], outTree[i]))